name: set git config
description: initialise git config so you can do stuff


inputs:
  ci_username:
    required: true
    description: "CI username"
  ci_user_email:
    required: true
    description: "CI user email"
  ci_access_token:
    required: true
    description: "CI access token"
    
runs:
  using: "composite"
  steps:
    - name: setup gitconfig
      run: |
        git config user.name "${{ inputs.ci_username }}"
        git config user.email "${{ inputs.ci_user_email }}"
        git config --global url."https://${{ inputs.ci_access_token }}@github.com/".insteadOf ssh://git@github.com

      shell: bash
